"""Pepsy boundary-contraction library package."""

from importlib import import_module
from importlib.metadata import PackageNotFoundError, version as _pkg_version
from typing import TYPE_CHECKING

try:
    __version__ = _pkg_version("pepsy")
except PackageNotFoundError:
    __version__ = "0+unknown"

_MODULE_EXPORTS = {
    "backends",
    "boundary",
    "fitting",
    "operators",
    "optimizers",
    "sampling",
    "solvers",
    "tensors",
    "vmc",
}

_SYMBOL_MODULES = {
    "BdyMPS": ".boundary",
    "BoundaryContractResult": ".boundary",
    "CompBdy": ".boundary",
    "boundary_norm": ".boundary",
    "build_bra_ket": ".boundary",
    "contract_boundary": ".boundary",
    "contract_flat": ".boundary",
    "infidelity": ".boundary",
    "make_numpy_array_caster": ".boundary",
    "normalize": ".boundary",
    "peps_fidelity": ".boundary",
    "peps_infidelity": ".boundary",
    "peps_norm": ".boundary",
    "peps_normalize": ".boundary",
    "backend_cupy": ".backends",
    "backend_jax": ".backends",
    "backend_numpy": ".backends",
    "backend_torch": ".backends",
    "get_default_array_backend": ".backends",
    "get_default_grad_backend": ".backends",
    "register_torch_linalg": ".backends",
    "reset_default_backends": ".backends",
    "set_default_array_backend": ".backends",
    "set_default_grad_backend": ".backends",
    "to_float": ".backends",
    "FIT": ".fitting",
    "internal_inds": ".fitting",
    "build_mpo_from_gates": ".operators",
    "build_pepo_from_gates": ".operators",
    "cnot": ".operators",
    "cphase": ".operators",
    "crx": ".operators",
    "cry": ".operators",
    "crz": ".operators",
    "cu1": ".operators",
    "cu2": ".operators",
    "cu3": ".operators",
    "cx": ".operators",
    "cy": ".operators",
    "cz": ".operators",
    "fsim": ".operators",
    "fsimg": ".operators",
    "gate": ".operators",
    "gate_simple": ".operators",
    "h": ".operators",
    "hadamard": ".operators",
    "ham_tn": ".operators",
    "iswap": ".operators",
    "pauli": ".operators",
    "phase": ".operators",
    "renorm_gauge": ".operators",
    "rx": ".operators",
    "rxx": ".operators",
    "ry": ".operators",
    "ryy": ".operators",
    "rz": ".operators",
    "rzz": ".operators",
    "s": ".operators",
    "sdg": ".operators",
    "su4": ".operators",
    "swap": ".operators",
    "t": ".operators",
    "tdg": ".operators",
    "u1": ".operators",
    "u2": ".operators",
    "u3": ".operators",
    "x": ".operators",
    "y": ".operators",
    "z": ".operators",
    "GlobalOptimizer": ".optimizers",
    "MpoOptimizer": ".optimizers",
    "MpsEnergyOptimizer": ".optimizers",
    "MpsOptimizer": ".optimizers",
    "PepsEnergyOptimizer": ".optimizers",
    "PepsOptimizer": ".optimizers",
    "SimpleUpdateGen": ".optimizers",
    "SymDMRG2": ".optimizers",
    "SweepOptimizer": ".optimizers",
    "MpsSampleResult": ".sampling",
    "MpsSampler": ".sampling",
    "PEPSSampleResult": ".sampling",
    "PepsBpSampler": ".sampling",
    "VecSampler": ".sampling",
    "FDSolver": ".solvers",
    "GradSolverResult": ".solvers",
    "GradientOptimizer": ".solvers",
    "SUPPORTED_SOLVERS": ".solvers",
    "optimize_packed_params": ".solvers",
    "OneDMap": ".tensors",
    "SymGateStream": ".tensors",
    "SymHamiltonian": ".tensors",
    "SymMPS": ".tensors",
    "SymPEPS": ".tensors",
    "add_cycle": ".tensors",
    "build_compressed_optimizer": ".tensors",
    "build_optimizer": ".tensors",
    "contract_hypercompressed_tn": ".tensors",
    "default_physical_sectors": ".tensors",
    "draw_symmray_blocks": ".tensors",
    "draw_symmray_mps": ".tensors",
    "draw_symmray_mpo": ".tensors",
    "draw_symmray_peps": ".tensors",
    "fermi_hubbard_u1u1_gate_stream": ".tensors",
    "fermi_hubbard_u1u1_hopping_gate_stream": ".tensors",
    "fermi_hubbard_u1u1_interaction_gate_stream": ".tensors",
    "fermi_hubbard_u1u1_light_pulse_gate_stream": ".tensors",
    "expec_mpo": ".tensors",
    "haar_random_state": ".tensors",
    "hrps_to_mps": ".tensors",
    "hrps_to_peps": ".tensors",
    "id_to_mpo": ".tensors",
    "id_to_pepo": ".tensors",
    "measure_obs": ".tensors",
    "ps_to_3dpeps": ".tensors",
    "ps_to_mpo": ".tensors",
    "ps_to_mps": ".tensors",
    "ps_to_pepo": ".tensors",
    "ps_to_peps": ".tensors",
    "random_haar_qubit": ".tensors",
    "reg_complex_qr_torch": ".tensors",
    "reg_complex_svd_jax": ".tensors",
    "reg_complex_svd_torch": ".tensors",
    "reg_real_qr_torch": ".tensors",
    "reg_real_svd_jax": ".tensors",
    "reg_real_svd_torch": ".tensors",
    "reg_rel_svd_jax": ".tensors",
    "reg_rel_svd_torch": ".tensors",
    "sector_index_map": ".tensors",
    "site_charge_alternating": ".tensors",
    "site_charge_from_map": ".tensors",
    "site_charge_from_occupations": ".tensors",
    "site_charge_uniform": ".tensors",
    "symmray_block_summary": ".tensors",
    "symmray_mps_summary": ".tensors",
    "symmray_mpo_summary": ".tensors",
    "symmray_peps_summary": ".tensors",
    "symm_operator_from_dense": ".tensors",
    "tn_fidelity": ".tensors",
    "tn_norm": ".tensors",
    "tns_align": ".tensors",
    "validate_tensor_network_tags": ".tensors",
}

__all__ = [
    "__version__",
    "backends",
    "boundary",
    "fitting",
    "operators",
    "optimizers",
    "sampling",
    "solvers",
    "tensors",
    "vmc",
    "BdyMPS",
    "BoundaryContractResult",
    "CompBdy",
    "boundary_norm",
    "build_bra_ket",
    "contract_boundary",
    "contract_flat",
    "infidelity",
    "make_numpy_array_caster",
    "normalize",
    "peps_fidelity",
    "peps_infidelity",
    "peps_norm",
    "peps_normalize",
    "get_default_array_backend",
    "get_default_grad_backend",
    "register_torch_linalg",
    "reset_default_backends",
    "set_default_array_backend",
    "set_default_grad_backend",
    "to_float",
    "FIT",
    "build_mpo_from_gates",
    "build_pepo_from_gates",
    "cnot",
    "cphase",
    "crx",
    "cry",
    "crz",
    "cu1",
    "cu2",
    "cu3",
    "cx",
    "cy",
    "cz",
    "fsim",
    "fsimg",
    "gate",
    "gate_simple",
    "h",
    "hadamard",
    "ham_tn",
    "iswap",
    "pauli",
    "phase",
    "renorm_gauge",
    "rx",
    "rxx",
    "ry",
    "ryy",
    "rz",
    "rzz",
    "s",
    "sdg",
    "su4",
    "swap",
    "t",
    "tdg",
    "u1",
    "u2",
    "u3",
    "x",
    "y",
    "z",
    "GlobalOptimizer",
    "MpoOptimizer",
    "MpsEnergyOptimizer",
    "MpsOptimizer",
    "PepsEnergyOptimizer",
    "PepsOptimizer",
    "SimpleUpdateGen",
    "SymDMRG2",
    "SweepOptimizer",
    "MpsSampleResult",
    "MpsSampler",
    "PEPSSampleResult",
    "PepsBpSampler",
    "VecSampler",
    "FDSolver",
    "OneDMap",
    "SymGateStream",
    "SymHamiltonian",
    "SymMPS",
    "SymPEPS",
    "default_physical_sectors",
    "draw_symmray_blocks",
    "draw_symmray_mps",
    "draw_symmray_mpo",
    "draw_symmray_peps",
    "fermi_hubbard_u1u1_gate_stream",
    "fermi_hubbard_u1u1_hopping_gate_stream",
    "fermi_hubbard_u1u1_interaction_gate_stream",
    "fermi_hubbard_u1u1_light_pulse_gate_stream",
    "expec_mpo",
    "haar_random_state",
    "hrps_to_mps",
    "hrps_to_peps",
    "id_to_mpo",
    "id_to_pepo",
    "measure_obs",
    "ps_to_3dpeps",
    "ps_to_mpo",
    "ps_to_mps",
    "ps_to_pepo",
    "ps_to_peps",
    "random_haar_qubit",
    "reg_complex_qr_torch",
    "reg_complex_svd_jax",
    "reg_complex_svd_torch",
    "reg_real_qr_torch",
    "reg_real_svd_jax",
    "reg_real_svd_torch",
    "reg_rel_svd_jax",
    "reg_rel_svd_torch",
    "sector_index_map",
    "site_charge_alternating",
    "site_charge_from_map",
    "site_charge_from_occupations",
    "site_charge_uniform",
    "symmray_block_summary",
    "symmray_mps_summary",
    "symmray_mpo_summary",
    "symmray_peps_summary",
    "symm_operator_from_dense",
    "tn_fidelity",
    "tn_norm",
    "tns_align",
]


def __getattr__(name):
    """Lazily import public API symbols and new package namespaces."""
    if name in _MODULE_EXPORTS:
        return import_module(f".{name}", __name__)
    if name in _SYMBOL_MODULES:
        module = import_module(_SYMBOL_MODULES[name], __name__)
        return getattr(module, name)
    raise AttributeError(f"module 'pepsy' has no attribute {name!r}")


if TYPE_CHECKING:
    from . import backends, boundary, fitting, operators, optimizers, sampling, solvers, tensors, vmc
    from .backends import (
        get_default_array_backend,
        get_default_grad_backend,
        register_torch_linalg,
        reset_default_backends,
        set_default_array_backend,
        set_default_grad_backend,
        to_float,
    )
    from .boundary import (
        BdyMPS,
        BoundaryContractResult,
        CompBdy,
        boundary_norm,
        build_bra_ket,
        contract_boundary,
        contract_flat,
        infidelity,
        make_numpy_array_caster,
        normalize,
        peps_fidelity,
        peps_infidelity,
        peps_norm,
        peps_normalize,
    )
    from .fitting import FIT
    from .operators import (
        build_mpo_from_gates,
        build_pepo_from_gates,
        cnot,
        cphase,
        crx,
        cry,
        crz,
        cu1,
        cu2,
        cu3,
        cx,
        cy,
        cz,
        fsim,
        fsimg,
        gate,
        gate_simple,
        h,
        hadamard,
        ham_tn,
        iswap,
        pauli,
        phase,
        renorm_gauge,
        rx,
        rxx,
        ry,
        ryy,
        rz,
        rzz,
        s,
        sdg,
        su4,
        swap,
        t,
        tdg,
        u1,
        u2,
        u3,
        x,
        y,
        z,
    )
    from .optimizers import GlobalOptimizer, MpoOptimizer, MpsEnergyOptimizer, MpsOptimizer, PepsEnergyOptimizer, PepsOptimizer, SimpleUpdateGen, SymDMRG2, SweepOptimizer
    from .sampling import MpsSampleResult, MpsSampler, PEPSSampleResult, PepsBpSampler, VecSampler
    from .solvers import FDSolver
    from .tensors import (
        OneDMap,
        SymGateStream,
        SymHamiltonian,
        SymMPS,
        SymPEPS,
        default_physical_sectors,
        draw_symmray_blocks,
        draw_symmray_mps,
        draw_symmray_mpo,
        draw_symmray_peps,
        fermi_hubbard_u1u1_gate_stream,
        fermi_hubbard_u1u1_hopping_gate_stream,
        fermi_hubbard_u1u1_interaction_gate_stream,
        fermi_hubbard_u1u1_light_pulse_gate_stream,
        expec_mpo,
        haar_random_state,
        hrps_to_mps,
        hrps_to_peps,
        id_to_mpo,
        id_to_pepo,
        measure_obs,
        ps_to_3dpeps,
        ps_to_mpo,
        ps_to_mps,
        ps_to_pepo,
        ps_to_peps,
        random_haar_qubit,
        reg_complex_qr_torch,
        reg_complex_svd_jax,
        reg_complex_svd_torch,
        reg_real_qr_torch,
        reg_real_svd_jax,
        reg_real_svd_torch,
        reg_rel_svd_jax,
        reg_rel_svd_torch,
        sector_index_map,
        site_charge_alternating,
        site_charge_from_map,
        site_charge_from_occupations,
        site_charge_uniform,
        symmray_block_summary,
        symmray_mps_summary,
        symmray_mpo_summary,
        symmray_peps_summary,
        symm_operator_from_dense,
        tn_fidelity,
        tn_norm,
        tns_align,
    )
