"""Tensor-network simulation, contraction, optimization, and sampling."""

from importlib import import_module
from importlib.metadata import PackageNotFoundError, version as _pkg_version
from typing import TYPE_CHECKING

try:
    __version__ = _pkg_version("pepsy")
except PackageNotFoundError:
    __version__ = "0+unknown"

# Canonical package namespaces. Keep advanced domains explicit so callers can
# discover the stable core without scanning every lazy symbol below.
_CORE_MODULES = (
    "backends",
    "boundary",
    "fitting",
    "interop",
    "operators",
    "optimizers",
    "sampling",
    "solvers",
    "tensors",
)
_ADVANCED_MODULES = ("bp", "experimental", "vmc")
_MODULE_EXPORTS = set(_CORE_MODULES) | set(_ADVANCED_MODULES)

_SYMBOL_MODULES = {
    # Boundary and backend helpers.
    "BdyMPS": ".boundary",
    "BoundaryContractResult": ".boundary",
    "BoundaryFitDiagnostic": ".boundary",
    "CompBdy": ".boundary",
    "boundary_norm": ".boundary",
    "build_bra_ket": ".boundary",
    "contract_boundary": ".boundary",
    "contract_flat": ".boundary",
    "infidelity": ".boundary",
    "make_numpy_array_caster": ".boundary",
    "normalize": ".boundary",
    "peps_fidelity": ".boundary",
    "peps_infidelity": ".boundary",
    "peps_norm": ".boundary",
    "peps_normalize": ".boundary",
    "backend_cupy": ".backends",
    "backend_infer": ".backends",
    "backend_jax": ".backends",
    "backend_numpy": ".backends",
    "backend_torch": ".backends",
    "build_backend": ".backends",
    "get_default_array_backend": ".backends",
    "get_default_grad_backend": ".backends",
    "get_torch_linalg_config": ".backends",
    "register_jax_linalg": ".backends",
    "register_torch_linalg": ".backends",
    "reset_linalg_registrations": ".backends",
    "reset_default_backends": ".backends",
    "set_default_array_backend": ".backends",
    "set_default_grad_backend": ".backends",
    "TorchLinalgConfig": ".backends",
    "to_float": ".backends",
    "FIT": ".fitting",
    "GuppyConversionError": ".interop",
    "GuppyGateStream": ".interop",
    "GuppyMeasurement": ".interop",
    "guppy_gate_stream": ".interop",
    "internal_inds": ".fitting",
    "build_mpo_from_gates": ".operators",
    "build_cluster_expansion_pepo": ".operators",
    "build_itf_cluster_expansion_pepo": ".operators",
    "ActivePEPOBlocks": ".operators",
    "ClusterExpansionReport": ".operators",
    "ClusterExpansionPlan": ".operators",
    "PauliPEPOTerm": ".operators",
    "PauliPEPOBasis": ".operators",
    "CompiledPEPOExp": ".operators",
    "build_pepo_from_gates": ".operators",
    "cnot": ".operators",
    "cphase": ".operators",
    "crx": ".operators",
    "cry": ".operators",
    "crz": ".operators",
    "cu1": ".operators",
    "cu2": ".operators",
    "cu3": ".operators",
    "cx": ".operators",
    "cy": ".operators",
    "cz": ".operators",
    "fsim": ".operators",
    "fsimg": ".operators",
    "gate": ".operators",
    "gate_simple": ".operators",
    "h": ".operators",
    "hadamard": ".operators",
    "ham_tn": ".operators",
    "iswap": ".operators",
    "pauli": ".operators",
    "phase": ".operators",
    "renorm_gauge": ".operators",
    "rx": ".operators",
    "rxx": ".operators",
    "ry": ".operators",
    "ryy": ".operators",
    "rz": ".operators",
    "rzz": ".operators",
    "s": ".operators",
    "sdg": ".operators",
    "su4": ".operators",
    "swap": ".operators",
    "t": ".operators",
    "tdg": ".operators",
    "u1": ".operators",
    "u2": ".operators",
    "u3": ".operators",
    "x": ".operators",
    "y": ".operators",
    "z": ".operators",
    "GlobalOptimizer": ".optimizers",
    "MpoOptimizer": ".optimizers",
    "MpoChannelEvent": ".optimizers",
    "MpsEnergyOptimizer": ".optimizers",
    "MpsOptimizer": ".optimizers",
    "MpsStabOptimizer": ".optimizers",
    "SimulatorCandidate": ".optimizers",
    "SimulatorPlan": ".optimizers",
    "SimulatorPlanner": ".optimizers",
    "recommend_simulator": ".optimizers",
    "DeferredInjectionRecord": ".optimizers",
    "DeferredInjectionReport": ".optimizers",
    "DeferredProjectionRecord": ".optimizers",
    "ImmediateInjectionReport": ".optimizers",
    "ImmediateProjectionRecord": ".optimizers",
    "MeasurementRecord": ".optimizers",
    "NormEventRecord": ".optimizers",
    "StabilizerMpsSettingsAdvice": ".optimizers",
    "StabilizerMpsRunResult": ".optimizers",
    "StabilizerTreeRunResult": ".optimizers",
    "StreamAnalysisRecord": ".optimizers",
    "CoalescedMeasurementRecord": ".optimizers",
    "CoherentCrosstalkModel": ".optimizers",
    "CoalescedSampleResult": ".optimizers",
    "CoalescedTrajectoryLeaf": ".optimizers",
    "CoalescedTrajectoryResult": ".optimizers",
    "ImportanceSamplingPolicy": ".optimizers",
    "LeakageRecord": ".optimizers",
    "NoisyResult": ".optimizers",
    "MpsNoisyResult": ".optimizers",
    "NoisyShotResult": ".optimizers",
    "PauliErrorModel": ".optimizers",
    "PauliFault": ".optimizers",
    "StimCircuitPlan": ".optimizers",
    "StimDetector": ".optimizers",
    "StimHerald": ".optimizers",
    "StimNoiseSample": ".optimizers",
    "StimObservable": ".optimizers",
    "StimObservableRecord": ".optimizers",
    "StimShotResult": ".optimizers",
    "StimSyndromeRecord": ".optimizers",
    "TrajectoryChannel": ".optimizers",
    "TrajectoryDiagnostics": ".optimizers",
    "TrajectoryEvent": ".optimizers",
    "TrajectoryStreamPlan": ".optimizers",
    "TrajectoryOutcome": ".optimizers",
    "TrajectoryRecord": ".optimizers",
    "TrajectoryMeasurementRecord": ".optimizers",
    "TrajectorySample": ".optimizers",
    "TrajectoryShotResult": ".optimizers",
    "STNState": ".optimizers",
    "StabilizerMpsSimulator": ".optimizers",
    "PepsEnergyOptimizer": ".optimizers",
    "PepsOptimizer": ".optimizers",
    "SimpleUpdateGen": ".optimizers",
    "SymDMRG2": ".optimizers",
    "SweepOptimizer": ".optimizers",
    "TreeEnergyOptimizer": ".optimizers",
    "TreeLayoutFinder": ".optimizers",
    "TreeMPO": ".optimizers",
    "TreeOptimizer": ".optimizers",
    "TreePlan": ".optimizers",
    "build_tree_operator": ".optimizers",
    "tree_mpo": ".optimizers",
    "square_lattice_zigzag": ".optimizers",
    "TreeStabOptimizer": ".optimizers",
    "TreeTensorNetwork": ".optimizers",
    "compile_stim_circuit": ".optimizers",
    "compile_trajectory_stream": ".optimizers",
    "run_coalesced_noisy_shots": ".optimizers",
    "run_coalesced_stim_shots": ".optimizers",
    "run_coalesced_trajectory_shots": ".optimizers",
    "MpsNoisy": ".optimizers",
    "TreeNoisy": ".optimizers",
    "run_noisy_shots": ".optimizers",
    "run_parallel_noisy_shots": ".optimizers",
    "run_parallel_stim_shots": ".optimizers",
    "run_parallel_trajectory_shots": ".optimizers",
    "run_stabilizer_mps_stream": ".optimizers",
    "run_stabilizer_tree_stream": ".optimizers",
    "run_stim_shots": ".optimizers",
    "run_trajectory_shots": ".optimizers",
    "sample_noisy_gate_stream": ".optimizers",
    "sample_noisy_gate_streams": ".optimizers",
    "sample_stim_circuit": ".optimizers",
    "sample_stim_circuits": ".optimizers",
    "sample_trajectory_stream": ".optimizers",
    "sample_coalesced_bits": ".optimizers",
    "FermionConfigurationEncoding": ".sampling",
    "MpsDiagonalEstimate": ".sampling",
    "MpsBatchSampleResult": ".sampling",
    "MpsSampleResult": ".sampling",
    "MpsSampler": ".sampling",
    "PEPSSampleResult": ".sampling",
    "PepsSampler": ".sampling",
    "PepsBpSampler": ".sampling",
    "VecSampler": ".sampling",
    "TreeBatchSampleResult": ".sampling",
    "TreeSampleResult": ".sampling",
    "TreeSampler": ".sampling",
    "FDSolver": ".solvers",
    "GradSolverResult": ".solvers",
    "GradientOptimizer": ".solvers",
    "SUPPORTED_SOLVERS": ".solvers",
    "optimize_packed_params": ".solvers",
    "OneDMap": ".tensors",
    "Fermion": ".tensors",
    "FermionLatticeSetup": ".tensors",
    "SpinfulFermion": ".tensors",
    "SpinfulFermionHubbard": ".tensors",
    "SymmFermions": ".tensors",
    "SymGateStream": ".tensors",
    "SymHamiltonian": ".tensors",
    "SymMPS": ".tensors",
    "SymPEPS": ".tensors",
    "add_cycle": ".tensors",
    "build_compressed_optimizer": ".tensors",
    "build_contraction": ".tensors",
    "build_optimizer": ".tensors",
    "contract_hypercompressed_tn": ".tensors",
    "contract_hypercompressed_tn_batch": ".tensors",
    "default_physical_sectors": ".tensors",
    "draw_symmray_blocks": ".tensors",
    "draw_symmray_mps": ".tensors",
    "draw_symmray_mpo": ".tensors",
    "draw_symmray_peps": ".tensors",
    "fermi_hubbard_u1u1_gate_stream": ".tensors",
    "fermi_hubbard_u1u1_hopping_gate_stream": ".tensors",
    "fermi_hubbard_u1u1_interaction_gate_stream": ".tensors",
    "fermi_hubbard_u1u1_light_pulse_gate_stream": ".tensors",
    "fermi_hubbard_u1u1_jw_gate_stream": ".tensors",
    "fermi_hubbard_u1u1_jw_hopping_gate_stream": ".tensors",
    "fermi_hubbard_u1u1_jw_interaction_gate_stream": ".tensors",
    "fermion_density_param_gen": ".tensors",
    "fermion_hopping_param_gen": ".tensors",
    "fermion_interaction_param_gen": ".tensors",
    "expec_mpo": ".tensors",
    "haar_random_state": ".tensors",
    "hrs_to_mps": ".tensors",
    "hrs_to_peps": ".tensors",
    "hrs_to_ttn": ".tensors",
    "hrps_to_mps": ".tensors",
    "hrps_to_peps": ".tensors",
    "hrps_to_ttn": ".tensors",
    "id_to_mpo": ".tensors",
    "id_to_pepo": ".tensors",
    "measure_obs": ".tensors",
    "ps_to_3dpeps": ".tensors",
    "ps_to_mpo": ".tensors",
    "ps_to_mps": ".tensors",
    "ps_to_ttn": ".tensors",
    "ps_to_pepo": ".tensors",
    "ps_to_peps": ".tensors",
    "random_haar_qubit": ".tensors",
    "reg_native_svd_jax": ".tensors",
    "reg_native_svd_torch": ".tensors",
    "reg_complex_qr_torch": ".tensors",
    "reg_complex_svd_jax": ".tensors",
    "reg_complex_svd_torch": ".tensors",
    "reg_real_qr_torch": ".tensors",
    "reg_real_svd_jax": ".tensors",
    "reg_real_svd_torch": ".tensors",
    "reg_rel_svd_jax": ".tensors",
    "reg_rel_svd_torch": ".tensors",
    "sector_index_map": ".tensors",
    "site_charge_alternating": ".tensors",
    "site_charge_from_map": ".tensors",
    "site_charge_from_occupations": ".tensors",
    "site_charge_uniform": ".tensors",
    "symmray_block_summary": ".tensors",
    "symmray_mps_summary": ".tensors",
    "symmray_mpo_summary": ".tensors",
    "symmray_peps_summary": ".tensors",
    "symm_operator_from_dense": ".tensors",
    "tn_fidelity": ".tensors",
    "tn_norm": ".tensors",
    "tns_align": ".tensors",
    "validate_tensor_network_tags": ".tensors",
    "gauge_all": ".bp",
    "gauge_all_simple": ".bp",
    "compress_all_gauge": ".bp",
    "one_norm_bp": ".bp",
}

__all__ = ["__version__", *_CORE_MODULES, *_ADVANCED_MODULES, *_SYMBOL_MODULES]


def __getattr__(name):
    """Lazily import public API symbols and new package namespaces."""
    if name in _MODULE_EXPORTS:
        return import_module(f".{name}", __name__)
    if name in _SYMBOL_MODULES:
        module = import_module(_SYMBOL_MODULES[name], __name__)
        return getattr(module, name)
    raise AttributeError(f"module 'pepsy' has no attribute {name!r}")


if TYPE_CHECKING:
    from .bp import compress_all_gauge, gauge_all, gauge_all_simple, one_norm_bp  # noqa: F401
    from . import backends, boundary, bp, experimental, fitting, interop, operators, optimizers, sampling, solvers, tensors, vmc  # noqa: F401
    from .interop import GuppyConversionError, GuppyGateStream, GuppyMeasurement, guppy_gate_stream  # noqa: F401
    from .backends import (  # noqa: F401
        backend_infer,
        get_default_array_backend,
        get_default_grad_backend,
        get_torch_linalg_config,
        build_backend,
        register_jax_linalg,
        register_torch_linalg,
        reset_linalg_registrations,
        reset_default_backends,
        set_default_array_backend,
        set_default_grad_backend,
        TorchLinalgConfig,
        to_float,
    )
    from .boundary import (  # noqa: F401
        BdyMPS,
        BoundaryContractResult,
        CompBdy,
        boundary_norm,
        build_bra_ket,
        contract_boundary,
        contract_flat,
        infidelity,
        make_numpy_array_caster,
        normalize,
        peps_fidelity,
        peps_infidelity,
        peps_norm,
        peps_normalize,
    )
    from .fitting import FIT  # noqa: F401
    from .operators import (  # noqa: F401
        ActivePEPOBlocks,
        ClusterExpansionReport,
        build_cluster_expansion_pepo,
        build_itf_cluster_expansion_pepo,
        ClusterExpansionPlan,
        PauliPEPOTerm,
        PauliPEPOBasis,
        CompiledPEPOExp,
        build_mpo_from_gates,
        build_pepo_from_gates,
        cnot,
        cphase,
        crx,
        cry,
        crz,
        cu1,
        cu2,
        cu3,
        cx,
        cy,
        cz,
        fsim,
        fsimg,
        gate,
        gate_simple,
        h,
        hadamard,
        ham_tn,
        iswap,
        pauli,
        phase,
        renorm_gauge,
        rx,
        rxx,
        ry,
        ryy,
        rz,
        rzz,
        s,
        sdg,
        su4,
        swap,
        t,
        tdg,
        u1,
        u2,
        u3,
        x,
        y,
        z,
    )
    from .optimizers import DeferredInjectionRecord, DeferredInjectionReport, DeferredProjectionRecord, GlobalOptimizer, ImmediateInjectionReport, ImmediateProjectionRecord, MeasurementRecord, MpoChannelEvent, MpoOptimizer, MpsEnergyOptimizer, MpsOptimizer, MpsStabOptimizer, NormEventRecord, PepsEnergyOptimizer, PepsOptimizer, STNState, StabilizerMpsSettingsAdvice, StabilizerMpsRunResult, StabilizerMpsSimulator, StabilizerTreeRunResult, StreamAnalysisRecord, SimpleUpdateGen, SymDMRG2, SweepOptimizer, TreeEnergyOptimizer, TreeLayoutFinder, TreeMPO, TreeOptimizer, TreePlan, TreeStabOptimizer, build_tree_operator, run_stabilizer_mps_stream, run_stabilizer_tree_stream  # noqa: F401
    from .sampling import FermionConfigurationEncoding, MpsDiagonalEstimate, MpsBatchSampleResult, MpsSampleResult, MpsSampler, PEPSSampleResult, PepsSampler, PepsBpSampler, TreeBatchSampleResult, TreeSampleResult, TreeSampler, VecSampler  # noqa: F401
    from .solvers import FDSolver  # noqa: F401
    from .tensors import (  # noqa: F401
        OneDMap,
        build_contraction,
        Fermion,
        FermionLatticeSetup,
        SpinfulFermion,
        SpinfulFermionHubbard,
        SymmFermions,
        SymGateStream,
        SymHamiltonian,
        SymMPS,
        SymPEPS,
        default_physical_sectors,
        draw_symmray_blocks,
        draw_symmray_mps,
        draw_symmray_mpo,
        draw_symmray_peps,
        fermi_hubbard_u1u1_gate_stream,
        fermi_hubbard_u1u1_hopping_gate_stream,
        fermi_hubbard_u1u1_interaction_gate_stream,
        fermi_hubbard_u1u1_light_pulse_gate_stream,
        fermi_hubbard_u1u1_jw_gate_stream,
        fermi_hubbard_u1u1_jw_hopping_gate_stream,
        fermi_hubbard_u1u1_jw_interaction_gate_stream,
        fermion_density_param_gen,
        fermion_hopping_param_gen,
        fermion_interaction_param_gen,
        expec_mpo,
        haar_random_state,
        hrs_to_mps,
        hrs_to_peps,
        hrs_to_ttn,
        hrps_to_mps,
        hrps_to_peps,
        hrps_to_ttn,
        id_to_mpo,
        id_to_pepo,
        measure_obs,
        ps_to_3dpeps,
        ps_to_mpo,
        ps_to_mps,
        ps_to_ttn,
        ps_to_pepo,
        ps_to_peps,
        random_haar_qubit,
        reg_native_svd_jax,
        reg_native_svd_torch,
        reg_complex_qr_torch,
        reg_complex_svd_jax,
        reg_complex_svd_torch,
        reg_real_qr_torch,
        reg_real_svd_jax,
        reg_real_svd_torch,
        reg_rel_svd_jax,
        reg_rel_svd_torch,
        sector_index_map,
        site_charge_alternating,
        site_charge_from_map,
        site_charge_from_occupations,
        site_charge_uniform,
        symmray_block_summary,
        symmray_mps_summary,
        symmray_mpo_summary,
        symmray_peps_summary,
        symm_operator_from_dense,
        tn_fidelity,
        tn_norm,
        tns_align,
    )
