"""Tensor-network simulation, contraction, optimization, and sampling."""

from importlib import import_module
from importlib.metadata import PackageNotFoundError, version as _pkg_version
from typing import TYPE_CHECKING

from ._api import _SYMBOL_MODULES

try:
    __version__ = _pkg_version("pepsy")
except PackageNotFoundError:
    __version__ = "0+unknown"

# Canonical package namespaces. Keep advanced domains explicit so callers can
# discover the stable core without scanning every lazy symbol below.
_CORE_MODULES = (
    "backends",
    "boundary",
    "fitting",
    "interop",
    "operators",
    "optimizers",
    "sampling",
    "solvers",
    "tensors",
)
_ADVANCED_MODULES = ("bp", "experimental", "vmc")
_MODULE_EXPORTS = set(_CORE_MODULES) | set(_ADVANCED_MODULES)

# Compatibility facade metadata stays in a private lazy-safe module. Keep
# existing aliases working, but add new functionality to its owning domain
# namespace instead of expanding this root module.

__all__ = ["__version__", *_CORE_MODULES, *_ADVANCED_MODULES, *_SYMBOL_MODULES]


def __dir__():
    """List available names without importing their implementations."""
    return sorted(set(globals()) | set(__all__))


def __getattr__(name):
    """Lazily import public API symbols and new package namespaces."""
    if name in _MODULE_EXPORTS:
        return import_module(f".{name}", __name__)
    if name in _SYMBOL_MODULES:
        module = import_module(_SYMBOL_MODULES[name], __name__)
        return getattr(module, name)
    raise AttributeError(f"module 'pepsy' has no attribute {name!r}")


if TYPE_CHECKING:
    from . import (  # noqa: F401
        backends,
        boundary,
        bp,
        experimental,
        fitting,
        interop,
        operators,
        optimizers,
        sampling,
        solvers,
        tensors,
        vmc,
    )
    from .backends import (  # noqa: F401
        TorchLinalgConfig,
        backend_cupy,
        backend_infer,
        backend_jax,
        backend_numpy,
        backend_torch,
        build_backend,
        get_default_array_backend,
        get_default_grad_backend,
        get_torch_linalg_config,
        register_jax_linalg,
        register_torch_linalg,
        reset_default_backends,
        reset_linalg_registrations,
        set_default_array_backend,
        set_default_grad_backend,
        to_float,
    )
    from .boundary import (  # noqa: F401
        BdyMPS,
        BoundaryContractResult,
        BoundaryFitDiagnostic,
        CompBdy,
        boundary_norm,
        build_bra_ket,
        contract_boundary,
        contract_flat,
        contract_layered,
        infidelity,
        make_numpy_array_caster,
        normalize,
        peps_fidelity,
        peps_infidelity,
        peps_norm,
        peps_normalize,
    )
    from .bp import (  # noqa: F401
        compress_all_gauge,
        gauge_all,
        gauge_all_simple,
        one_norm_bp,
    )
    from .fitting import (  # noqa: F401
        FIT,
        internal_inds,
    )
    from .interop import (  # noqa: F401
        GuppyConversionError,
        GuppyGateStream,
        GuppyMeasurement,
        guppy_gate_stream,
    )
    from .operators import (  # noqa: F401
        ActivePEPOBlocks,
        ClusterExpansionPlan,
        ClusterExpansionReport,
        ClusterInternalSymmetry,
        ClusterLattice,
        ClusterModelAdapter,
        CompiledPEPOClusterProduct,
        CompiledPEPOExp,
        ConnectedClusterShape,
        GraphActivePEPOBlocks,
        GraphClusterExpansionPlan,
        GraphConnectedClusterShape,
        PEPOClusterFactor,
        PEPOClusterProductExpansion,
        PauliPEPOBasis,
        PauliPEPOTerm,
        adapt_cluster_model,
        build_cluster_expansion_pepo,
        build_graph_cluster_expansion_pepo,
        build_itf_cluster_expansion_pepo,
        build_model_cluster_expansion_pepo,
        build_mpo_from_gates,
        build_pepo_from_gates,
        build_real_time_cluster_expansion_pepo,
        cnot,
        compose_cluster_expansion_pepo,
        compose_pepo_layers,
        compress_mpo_product,
        cphase,
        crx,
        cry,
        crz,
        cu1,
        cu2,
        cu3,
        cx,
        cy,
        cz,
        fsim,
        fsimg,
        gate,
        gate_mpo_auto_swap,
        gate_simple,
        generate_connected_cluster_shapes,
        h,
        hadamard,
        ham_tn,
        iswap,
        pauli,
        phase,
        renorm_gauge,
        rx,
        rxx,
        ry,
        ryy,
        rz,
        rzz,
        s,
        sdg,
        su4,
        swap,
        t,
        tdg,
        u1,
        u2,
        u3,
        x,
        y,
        z,
    )
    from .optimizers import (  # noqa: F401
        CoalescedMeasurementRecord,
        CoalescedSampleResult,
        CoalescedTrajectoryLeaf,
        CoalescedTrajectoryResult,
        CoherentCrosstalkModel,
        DeferredInjectionRecord,
        DeferredInjectionReport,
        DeferredProjectionRecord,
        GibbsMps,
        GlobalOptimizer,
        ImmediateInjectionReport,
        ImmediateProjectionRecord,
        ImportanceSamplingPolicy,
        LeakageRecord,
        MPIRankDiagnostics,
        MPIShotError,
        MPIShotResult,
        MPIShotRunner,
        MeasurementRecord,
        MpoChannelEvent,
        MpoOptimizer,
        MpsEnergyOptimizer,
        MpsOptimizer,
        MpsStabOptimizer,
        NoisyResult,
        NoisyShotResult,
        NormEventRecord,
        PauliErrorModel,
        PauliFault,
        PepsEnergyOptimizer,
        PepsOptimizer,
        STNState,
        SimpleUpdateGen,
        SimulatorCandidate,
        SimulatorPlan,
        SimulatorPlanner,
        StabilizerMpsRunResult,
        StabilizerMpsSettingsAdvice,
        StabilizerMpsSimulator,
        StabilizerTreeRunResult,
        StabilizerTreeSimulator,
        StimCircuitPlan,
        StimDetector,
        StimHerald,
        StimNoiseSample,
        StimObservable,
        StimObservableRecord,
        StimShotResult,
        StimSyndromeRecord,
        StreamAnalysisRecord,
        SubTreeMPO,
        SweepOptimizer,
        SymDMRG2,
        TrajectoryChannel,
        TrajectoryDiagnostics,
        TrajectoryEvent,
        TrajectoryMeasurementRecord,
        TrajectoryOutcome,
        TrajectoryRecord,
        TrajectorySample,
        TrajectoryShotResult,
        TrajectoryStreamPlan,
        TreeEnergyOptimizer,
        TreeLayoutFinder,
        TreeMPO,
        TreeNoisy,
        TreeOptimizer,
        TreePEPO,
        TreePepo,
        TreePeps,
        TreePepsGeometry,
        TreePepsLayoutFinder,
        TreePepsOptimizer,
        TreePepsPlan,
        TreePlan,
        TreeStabOptimizer,
        TreeSubPEPO,
        TreeSubPepo,
        TreeTensorNetwork,
        build_tree_operator,
        compile_stim_circuit,
        compile_trajectory_stream,
        recommend_simulator,
        run_coalesced_noisy_shots,
        run_coalesced_stim_shots,
        run_coalesced_trajectory_shots,
        run_mpi_shots,
        run_noisy_shots,
        run_parallel_noisy_shots,
        run_parallel_stim_shots,
        run_parallel_trajectory_shots,
        run_stabilizer_mps_stream,
        run_stabilizer_tree_stream,
        run_stim_shots,
        run_trajectory_shots,
        sample_coalesced_bits,
        sample_noisy_gate_stream,
        sample_noisy_gate_streams,
        sample_stim_circuit,
        sample_stim_circuits,
        sample_trajectory_stream,
        square_lattice_zigzag,
    )
    from .sampling import (  # noqa: F401
        FermionConfigurationEncoding,
        MpsBatchSampleResult,
        MpsDiagonalEstimate,
        MpsSampleResult,
        MpsSampler,
        MpsStabSampler,
        PEPSSampleResult,
        PepsBpSampler,
        PepsSampler,
        StabilizerMpsSampler,
        TreeBatchSampleResult,
        TreeSampleResult,
        TreeSampler,
        VecSampler,
    )
    from .solvers import (  # noqa: F401
        FDSolver,
        GradSolverResult,
        GradientOptimizer,
        SUPPORTED_SOLVERS,
        optimize_packed_params,
    )
    from .tensors import (  # noqa: F401
        Fermion,
        FermionLatticeSetup,
        OneDMap,
        SpinfulFermion,
        SpinfulFermionHubbard,
        SymGateStream,
        SymHamiltonian,
        SymMPS,
        SymPEPS,
        SymmFermions,
        add_cycle,
        bell_to_mps,
        build_compressed_optimizer,
        build_contraction,
        build_optimizer,
        contract_hypercompressed_tn,
        contract_hypercompressed_tn_batch,
        default_physical_sectors,
        draw_symmray_blocks,
        draw_symmray_mpo,
        draw_symmray_mps,
        draw_symmray_peps,
        expec_mpo,
        fermi_hubbard_u1u1_gate_stream,
        fermi_hubbard_u1u1_hopping_gate_stream,
        fermi_hubbard_u1u1_interaction_gate_stream,
        fermi_hubbard_u1u1_jw_gate_stream,
        fermi_hubbard_u1u1_jw_hopping_gate_stream,
        fermi_hubbard_u1u1_jw_interaction_gate_stream,
        fermi_hubbard_u1u1_light_pulse_gate_stream,
        fermion_density_param_gen,
        fermion_hopping_param_gen,
        fermion_interaction_param_gen,
        haar_random_state,
        hrps_to_mps,
        hrps_to_peps,
        hrps_to_ttn,
        hrs_to_mps,
        hrs_to_peps,
        hrs_to_ttn,
        id_to_mpo,
        id_to_pepo,
        measure_obs,
        mps_to_treepeps,
        mps_to_ttn,
        ps_to_3dpeps,
        ps_to_mpo,
        ps_to_mps,
        ps_to_pepo,
        ps_to_peps,
        ps_to_ttn,
        random_haar_qubit,
        reg_complex_qr_torch,
        reg_complex_svd_jax,
        reg_complex_svd_torch,
        reg_native_svd_jax,
        reg_native_svd_torch,
        reg_real_qr_torch,
        reg_real_svd_jax,
        reg_real_svd_torch,
        reg_rel_svd_jax,
        reg_rel_svd_torch,
        sector_index_map,
        site_charge_alternating,
        site_charge_from_map,
        site_charge_from_occupations,
        site_charge_uniform,
        symm_operator_from_dense,
        symmray_block_summary,
        symmray_mpo_summary,
        symmray_mps_summary,
        symmray_peps_summary,
        tn_fidelity,
        tn_norm,
        tns_align,
        validate_tensor_network_tags,
    )
