"""Belief-propagation contraction tools for pepsy (project plan section 1).

This subpackage wraps quimb's belief propagation and exposes the BP
contractions and corrections used by Pepsy:

* :func:`relay_bp` -- the disordered-memory / relay-BP extension that hardens
  the 1-norm or dense 2-norm BP *fixed point* (arXiv:2506.01779).
  :func:`one_norm_bp` and :func:`two_norm_bp` provide the corresponding plain
  runners.
* :func:`loop_cluster_expand` -- the loop cluster expansion (arXiv:2510.05647),
* :func:`loop_series_expand` -- the edge-resolved ``P + Q`` loop series
  (arXiv:2409.03108),
* :func:`partial_trace_loop_cluster_expand` -- a D2BP loop-cluster reduced
  density matrix and its scalar expectation companion,
* :func:`partial_trace_loop_series_expand` -- a D2BP reduced-density-matrix
  loop series and scalar local-observable companion,
* :func:`partial_trace_open_loop_series_expand` -- an explicit open-edge
  rho series retaining long-range excitation paths and closed loops,
* :func:`partial_trace_open_loop_series_sweep` -- one-BP multi-support,
  multi-cutoff open-rho diagnostics,
* :func:`compute_local_expectation_open_loop_series` -- direct gate-inserted
  scalar expectations from the same open paths and loops,
* :func:`loop_expand` -- an explicit selector between the correction families.
* :func:`partitioned_expand` -- the partitioned network expansion (PNE,
  arXiv:2512.10910), with :func:`recursive_partitioned_expand` for fixed
  recursive schedules. :func:`weight_pass` supplies higher-rank projectors.
* :func:`compress_reduced_loop_cluster` -- BP/SU-closed reduced-bond
  compression for dense PEPS and PEPO networks.
* :func:`compress_bond_cluster` -- gate-free compression of one selected bond
  with variational rectangular maps and a BP/SU cluster environment.

Most BP tools are imported explicitly as ``pepsy.bp``. The supported top-level
workflow entry points are :func:`pepsy.one_norm_bp`, :func:`pepsy.gauge_all`,
and :func:`pepsy.gauge_all_simple`.
"""

from .cluster import (
    BPCandidateScore,
    BPCandidateSelection,
    ConnectedLoop,
    LinkedClusterCache,
    LinkedClusterResult,
    LinkedClusterTerm,
    ScalarClusterCache,
    LoopClusterResult,
    linked_cluster_expand,
    loop_cluster_expand,
    norm1_gloop_expand,
    select_bp_candidate,
)
from .series import (
    OpenLoopBudgetError,
    OpenLoopAdaptiveResult,
    OpenLoopEnumerationLimitError,
    OpenLoopMeasurementResult,
    OpenLoopObservableTerm,
    OpenLoopSeriesDiagnostic,
    OpenLoopSeriesDiagnosticCache,
    OpenLoopSeriesCache,
    OpenLoopSeriesSweepResult,
    LoopSeriesCache,
    LoopSeriesResult,
    LoopSeriesTerm,
    compute_local_expectation_edge_loop_series,
    compute_local_expectation_open_loop_series,
    compute_local_expectation_loop_cluster,
    compute_local_expectation_loop_series,
    partial_trace_edge_loop_series_expand,
    partial_trace_open_loop_series_expand,
    partial_trace_open_loop_series_sweep,
    diagnose_open_loop_series,
    diagnose_open_rho_series,
    adaptive_open_loop_series,
    partial_trace_loop_cluster_expand,
    partial_trace_loop_series_expand,
    loop_series_expand,
)
from .expansion import loop_expand
from .pne import (
    PNEExpansionResult,
    PNEExpansionTerm,
    PNEPartitionScore,
    PNEPartitionSelection,
    RecursivePNEExpansionResult,
    pne_expand,
    pne_projector_diagnostics,
    pne_projectors,
    partitioned_expand,
    recursive_partitioned_expand,
    select_pne_partitions,
)
from .weights import WeightPassingResult, weight_pass
from .gauges import (
    GaugeResult,
    RelayGaugeOptions,
    compare_simple_update_gauges,
    compare_simple_update_to_bp,
    copy_gauges,
    d1bp_from_simple_update_gauges,
    d2bp_from_simple_update_gauges,
    gauge_all,
    gauge_all_simple,
    gauge_all_simple_with_bp_check,
    relay_gauge_all_simple,
    run_d1bp_from_simple_update_gauges,
    run_d2bp_from_simple_update_gauges,
    simple_update_bp_residual,
    simple_update_core_and_gauges_from_d2bp,
    simple_update_core_and_gauges_from_messages,
    simple_update_gauges_from_messages,
    simple_update_messages_from_gauges,
)
from .relay import (
    BPState,
    BPUpdateResult,
    RelayBPResult,
    one_norm_bp,
    relay_bp,
    two_norm_bp,
)
from .observables import (
    compute_boundary_expectation,
    compute_bp_path_expectation,
    compute_path_cluster_expectation,
)
from .compression import BondClusterCompressionResult, compress_bond_cluster
from ._compression_utils import CompressionBudgetError, ContractionCost
from .reduced_update import (
    ExactReducedUpdateProblem,
    LoopClusterReducedUpdateProblem,
    LoopClusterTerm,
    ReducedALSSolution,
    ReducedBondPair,
    ReducedLoopClusterCompressionResult,
    ReducedLoopClusterGateResult,
    ReducedUpdateProblem,
    SUClusterReducedUpdateProblem,
    apply_reduced_loop_cluster_gate,
    compress_reduced_loop_cluster,
    exact_reduced_update_problem,
    loop_cluster_reduced_update_problem,
    prepare_reduced_bond_pair,
    solve_reduced_als,
    su_cluster_reduced_update_problem,
)

__all__ = [
    "GaugeResult",
    "BondClusterCompressionResult",
    "CompressionBudgetError",
    "ContractionCost",
    "ExactReducedUpdateProblem",
    "BPCandidateScore",
    "BPCandidateSelection",
    "BPState",
    "BPUpdateResult",
    "ConnectedLoop",
    "LinkedClusterCache",
    "LinkedClusterResult",
    "LinkedClusterTerm",
    "LoopClusterReducedUpdateProblem",
    "LoopClusterResult",
    "LoopClusterTerm",
    "LoopSeriesCache",
    "OpenLoopSeriesCache",
    "OpenLoopEnumerationLimitError",
    "OpenLoopObservableTerm",
    "OpenLoopSeriesDiagnostic",
    "OpenLoopSeriesDiagnosticCache",
    "OpenLoopBudgetError",
    "OpenLoopAdaptiveResult",
    "OpenLoopMeasurementResult",
    "OpenLoopSeriesSweepResult",
    "LoopSeriesResult",
    "LoopSeriesTerm",
    "compute_local_expectation_edge_loop_series",
    "compute_local_expectation_open_loop_series",
    "diagnose_open_loop_series",
    "diagnose_open_rho_series",
    "adaptive_open_loop_series",
    "compute_local_expectation_loop_cluster",
    "compute_local_expectation_loop_series",
    "partial_trace_edge_loop_series_expand",
    "partial_trace_open_loop_series_expand",
    "partial_trace_open_loop_series_sweep",
    "partial_trace_loop_cluster_expand",
    "partial_trace_loop_series_expand",
    "RelayGaugeOptions",
    "ReducedALSSolution",
    "ReducedBondPair",
    "ReducedLoopClusterCompressionResult",
    "ReducedLoopClusterGateResult",
    "ReducedUpdateProblem",
    "SUClusterReducedUpdateProblem",
    "ScalarClusterCache",
    "apply_reduced_loop_cluster_gate",
    "compress_bond_cluster",
    "compress_reduced_loop_cluster",
    "compare_simple_update_gauges",
    "compare_simple_update_to_bp",
    "copy_gauges",
    "d1bp_from_simple_update_gauges",
    "d2bp_from_simple_update_gauges",
    "exact_reduced_update_problem",
    "gauge_all",
    "gauge_all_simple",
    "gauge_all_simple_with_bp_check",
    "relay_gauge_all_simple",
    "RelayBPResult",
    "loop_cluster_reduced_update_problem",
    "loop_cluster_expand",
    "linked_cluster_expand",
    "norm1_gloop_expand",
    "loop_series_expand",
    "loop_expand",
    "PNEExpansionResult",
    "PNEExpansionTerm",
    "PNEPartitionScore",
    "PNEPartitionSelection",
    "RecursivePNEExpansionResult",
    "WeightPassingResult",
    "pne_expand",
    "pne_projector_diagnostics",
    "pne_projectors",
    "partitioned_expand",
    "recursive_partitioned_expand",
    "select_pne_partitions",
    "weight_pass",
    "one_norm_bp",
    "prepare_reduced_bond_pair",
    "relay_bp",
    "run_d1bp_from_simple_update_gauges",
    "run_d2bp_from_simple_update_gauges",
    "simple_update_bp_residual",
    "simple_update_core_and_gauges_from_d2bp",
    "simple_update_core_and_gauges_from_messages",
    "simple_update_gauges_from_messages",
    "simple_update_messages_from_gauges",
    "select_bp_candidate",
    "solve_reduced_als",
    "su_cluster_reduced_update_problem",
    "two_norm_bp",
    "compute_boundary_expectation",
    "compute_path_cluster_expectation",
    "compute_bp_path_expectation",
]
