"""Canonical qMERA energy optimization helpers."""

from .builders import QMeraAnsatz, QMeraBuilder
from .cache import QMeraContractionPathCache, build_qmera_contraction_optimizer
from .compiled import (
    QMeraCompiledLightconeChunk,
    compile_qmera_parametric_lightcone,
    compile_qmera_parametric_lightcones,
    local_qmera_compiled_lightcone_expectation,
    qmera_compiled_parametric_energy,
)
from .fermions import (
    QMeraSymmrayFermionBackend,
    qmera_symmray_fermi_hubbard_terms,
    qmera_symmray_majorana_terms,
    symmray_fermion_gate_registry,
    symmray_majorana_gate_registry,
)
from .gates import (
    GateRegistry,
    GateSpec,
    UserGateFamily,
    default_gate_registry,
    resolve_gate_spec,
)
from .geometry import QMeraGeometry
from .layout import (
    QMeraLayoutCandidate,
    QMeraLayoutFinder,
    QMeraLayoutReport,
    QMeraLayoutScore,
)
from .lightcones import (
    QMeraLightconeTN,
    QMeraLightconeGroup,
    QMeraParametricLightconeChunk,
    build_qmera_lightcone_chunks,
    build_qmera_parametric_lightcone_chunks,
    contract_qmera_lightcone_group,
    contract_qmera_lightcone_tn,
    group_qmera_parametric_lightcone_chunks,
    local_qmera_parametric_lightcone_expectation,
    qmera_parametric_energy,
    qmera_direct_parametric_energy,
    qmera_parametric_lightcone_group_state,
    qmera_parametric_state,
    qmera_parametric_lightcone_state,
    qmera_parametric_lightcone_tn,
    select_lightcone,
    site_tags_for_where,
)
from .parametric import QMeraEnergyOptimizer, QMeraParametricEnergyOptimizer
from .prototype import QMeraPrototypeLayout, load_qmera_prototype_layout
from .schedules import (
    QMeraBlockSpec,
    QMeraDisentanglerSpec,
    QMeraGatePlacement,
    QMeraIsometrySpec,
    QMeraLayerSpec,
    QMeraScaleSpec,
    QMeraSchedule,
    QMeraUnitarySpec,
    build_qmera_schedule,
)
from .schematics import (
    QMeraSchematicBlock,
    draw_qmera_schedule,
    qmera_schematic_blocks,
)
from .terms import LocalTerm, normalize_local_terms

__all__ = [
    "GateRegistry",
    "GateSpec",
    "LocalTerm",
    "QMeraAnsatz",
    "QMeraBlockSpec",
    "QMeraBuilder",
    "QMeraCompiledLightconeChunk",
    "QMeraContractionPathCache",
    "QMeraDisentanglerSpec",
    "QMeraEnergyOptimizer",
    "QMeraGatePlacement",
    "QMeraGeometry",
    "QMeraIsometrySpec",
    "QMeraLayerSpec",
    "QMeraLayoutCandidate",
    "QMeraLayoutFinder",
    "QMeraLayoutReport",
    "QMeraLayoutScore",
    "QMeraLightconeTN",
    "QMeraLightconeGroup",
    "QMeraParametricLightconeChunk",
    "QMeraParametricEnergyOptimizer",
    "QMeraPrototypeLayout",
    "QMeraSchedule",
    "QMeraScaleSpec",
    "QMeraSchematicBlock",
    "QMeraSymmrayFermionBackend",
    "QMeraUnitarySpec",
    "UserGateFamily",
    "build_qmera_contraction_optimizer",
    "build_qmera_lightcone_chunks",
    "build_qmera_parametric_lightcone_chunks",
    "build_qmera_schedule",
    "compile_qmera_parametric_lightcone",
    "compile_qmera_parametric_lightcones",
    "contract_qmera_lightcone_tn",
    "contract_qmera_lightcone_group",
    "default_gate_registry",
    "draw_qmera_schedule",
    "group_qmera_parametric_lightcone_chunks",
    "local_qmera_compiled_lightcone_expectation",
    "local_qmera_parametric_lightcone_expectation",
    "load_qmera_prototype_layout",
    "normalize_local_terms",
    "qmera_compiled_parametric_energy",
    "qmera_direct_parametric_energy",
    "qmera_parametric_energy",
    "qmera_parametric_lightcone_group_state",
    "qmera_parametric_lightcone_state",
    "qmera_parametric_state",
    "qmera_parametric_lightcone_tn",
    "qmera_schematic_blocks",
    "qmera_symmray_fermi_hubbard_terms",
    "qmera_symmray_majorana_terms",
    "resolve_gate_spec",
    "select_lightcone",
    "site_tags_for_where",
    "symmray_fermion_gate_registry",
    "symmray_majorana_gate_registry",
]
