"""High-level tensor-network optimizers."""

from importlib import import_module

from .energy import EnergyEstimate, MpsEnergyOptimizer, PepsEnergyOptimizer
from .global_opt import GlobalOptimizer
from .mera import (
    MeraEnergyOptimizer,
    QMeraBuilder,
    QMeraGeometry,
    QMeraParametricEnergyOptimizer,
    build_qmera_contraction_optimizer,
)
from .mpo import MpoOptimizer
from .mps import MpsOptimizer
from .noise import (
    CoalescedMeasurementRecord,
    CoalescedSampleResult,
    CoalescedTrajectoryLeaf,
    CoalescedTrajectoryResult,
    LeakageRecord,
    NoisyShotResult,
    PauliErrorModel,
    PauliFault,
    StimCircuitPlan,
    StimHerald,
    StimNoiseSample,
    StimShotResult,
    TrajectoryChannel,
    TrajectoryEvent,
    TrajectoryOutcome,
    TrajectoryRecord,
    TrajectorySample,
    TrajectoryShotResult,
    compile_stim_circuit,
    run_coalesced_noisy_shots,
    run_coalesced_stim_shots,
    run_coalesced_trajectory_shots,
    run_noisy_shots,
    run_stim_shots,
    run_trajectory_shots,
    sample_noisy_gate_stream,
    sample_noisy_gate_streams,
    sample_stim_circuit,
    sample_stim_circuits,
    sample_trajectory_stream,
    sample_coalesced_bits,
)
from .peps import PepsOptimizer, SimpleUpdateGen
from .stabilizer_tn import (
    DeferredInjectionRecord,
    DeferredInjectionReport,
    DeferredProjectionRecord,
    ImmediateInjectionReport,
    ImmediateProjectionRecord,
    MeasurementRecord,
    MpsStabOptimizer,
    NormEventRecord,
    STNState,
    StabilizerMpsSettingsAdvice,
    StabilizerMpsSimulator,
    StabilizerMpsRunResult,
    StreamAnalysisRecord,
    run_stabilizer_mps_stream,
)
from .sym_dmrg import SymDMRG2
from .sweep import SweepOptimizer
from .tree import TreeOptimizer

__all__ = [
    "CoalescedMeasurementRecord",
    "CoalescedSampleResult",
    "CoalescedTrajectoryLeaf",
    "CoalescedTrajectoryResult",
    "EnergyEstimate",
    "GlobalOptimizer",
    "DeferredInjectionRecord",
    "DeferredInjectionReport",
    "DeferredProjectionRecord",
    "ImmediateInjectionReport",
    "ImmediateProjectionRecord",
    "LeakageRecord",
    "MeasurementRecord",
    "MeraEnergyOptimizer",
    "MpoOptimizer",
    "MpsEnergyOptimizer",
    "MpsOptimizer",
    "MpsStabOptimizer",
    "NormEventRecord",
    "NoisyShotResult",
    "PauliErrorModel",
    "PauliFault",
    "StimCircuitPlan",
    "StimHerald",
    "StimNoiseSample",
    "StimShotResult",
    "TrajectoryChannel",
    "TrajectoryEvent",
    "TrajectoryOutcome",
    "TrajectoryRecord",
    "TrajectorySample",
    "TrajectoryShotResult",
    "STNState",
    "StabilizerMpsSettingsAdvice",
    "StabilizerMpsSimulator",
    "StabilizerMpsRunResult",
    "StreamAnalysisRecord",
    "PepsEnergyOptimizer",
    "PepsOptimizer",
    "QMeraBuilder",
    "QMeraGeometry",
    "QMeraParametricEnergyOptimizer",
    "SimpleUpdateGen",
    "SymDMRG2",
    "SweepOptimizer",
    "TreeOptimizer",
    "compile_stim_circuit",
    "build_qmera_contraction_optimizer",
    "run_coalesced_noisy_shots",
    "run_coalesced_stim_shots",
    "run_coalesced_trajectory_shots",
    "run_noisy_shots",
    "run_stabilizer_mps_stream",
    "run_stim_shots",
    "run_trajectory_shots",
    "sample_noisy_gate_stream",
    "sample_noisy_gate_streams",
    "sample_stim_circuit",
    "sample_stim_circuits",
    "sample_trajectory_stream",
    "sample_coalesced_bits",
    "energy",
    "global_opt",
    "mera",
    "mpo",
    "mps",
    "peps",
    "stabilizer_tn",
    "sym_dmrg",
    "sweep",
    "tree",
]


def __getattr__(name):
    if name in {
        "energy",
        "global_opt",
        "mera",
        "mpo",
        "mps",
        "noise",
        "peps",
        "stabilizer_tn",
        "sym_dmrg",
        "sweep",
        "tree",
    }:
        return import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
